FROM golang:1.16

WORKDIR /app

COPY go.mod ./
COPY static ./static/
COPY templates ./templates/

RUN go mod download

COPY *.go ./

RUN go build -o /simple-fortune-cookie-frontend

Expose 9000

CMD [ "/simple-fortune-cookie-frontend" ]