
version: '3.4'

services:
    database:
        image: redis

    backend:
        image: simple-fortune-cookie-backend
        build: backend/.
        ports:
            - 9000:9000
        environment:
            REDIS_DNS: database
        
    frontend:
        image: simple-fortune-cookie-frontend
        build: frontend/.
        ports:
            - 8080:8080
        environment:
            BACKEND_DNS: backend
            BACKEND_PORT: 9000
            