
version: '3.4'

services:
    backend:
        image: simple-fortune-cookie-backend
        build: backend/.
        
    frontend:
        image: simple-fortune-cookie-frontend
        build: frontend/.
        ports:
            - 8080:8080