
FROM golang:1.16-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./

RUN go build -o /simple-fortune-cookie-backend

Expose 9000

CMD [ "/simple-fortune-cookie-backend" ]