# action.yml
name: fortune-cookie
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: ls
      - name: checkout
        run: chmod +x docker build -t test -f backend/dockerfile /home/ubuntu/simple-fortune-cookie-2/backend