# action.yml
name: fortune-cookie
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: ls
      - name: build
        run: docker-compose up -d --build
      - name: curl
        run: curl localhost:9000
